import { Geist, Geist_Mono } from "next/font/google";
import "@/assets/styles/globals.css";
import { LandingLayout } from "@/component/layout/landing-layout";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <LandingLayout>{children}</LandingLayout>
      </body>
    </html>
  );
}
